version: "3"
services:
    ssserver:
        command: ["ssserver", "-c", "/etc/ssserver.json"]
        container_name: dc-ssserver
        image: cyclopszhao/shadowsocks:latest
        networks:
            - gfw-wtf
        ports:
        - 8388:8388
        restart: on-failure
        tty: true
        volumes: 
        - ./ssserver.json:/etc/ssserver.json
    kcptun:
        command: [
            "server_linux_amd64",
            "-c", "/etc/kcptun.json",
            # "--log", "/var/log/kcptun.log"
        ]
        container_name: dc-kcptun-server
        depends_on:
        - ssserver
        image: cyclopszhao/kcptun:latest
        networks:
            - gfw-wtf
        ports:
        - 29900:29900/udp
        restart: on-failure
        tty: true
        volumes:
        - ./kcptun-server.json:/etc/kcptun.json

networks:
    gfw-wtf:
        driver: bridge

